// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZhH9oKNxy523s8WggaqamOdTCBpRZCs',
    appId: '1:232925783602:web:8829380c6d75b13aa7be2b',
    messagingSenderId: '232925783602',
    projectId: 'itsula-anadan',
    authDomain: 'itsula-anadan.firebaseapp.com',
    storageBucket: 'itsula-anadan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixca1YQ_3HxFuNQYX18nntMJwmbi2Ces',
    appId: '1:232925783602:android:518bb161ec7f3eaca7be2b',
    messagingSenderId: '232925783602',
    projectId: 'itsula-anadan',
    storageBucket: 'itsula-anadan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEm8PofnLEzLrMt8PHXPiMtZIOITcRCyI',
    appId: '1:232925783602:ios:4d72202f23a01256a7be2b',
    messagingSenderId: '232925783602',
    projectId: 'itsula-anadan',
    storageBucket: 'itsula-anadan.appspot.com',
    iosBundleId: 'com.example.itsula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEm8PofnLEzLrMt8PHXPiMtZIOITcRCyI',
    appId: '1:232925783602:ios:c0b4234299a61eefa7be2b',
    messagingSenderId: '232925783602',
    projectId: 'itsula-anadan',
    storageBucket: 'itsula-anadan.appspot.com',
    iosBundleId: 'com.example.itsula.RunnerTests',
  );
}
